#!/usr/bin/env bash
# Runway — one-line install.
#
#   curl -fsSL https://raw.githubusercontent.com/Dvorinka/runway/main/install.sh | bash
#
# Installs into ./runway (override with RUNWAY_DIR), generates secrets,
# builds the image, and starts the stack. Non-interactive; re-runs never
# overwrite an existing .env.
#
# Env overrides:
#   RUNWAY_DIR       install directory           (default ./runway)
#   RUNWAY_REF       git ref to install          (default main)
#   RUNWAY_VERSION   release tag alias for RUNWAY_REF
#   HTTP_PORT        published http port         (default 80)
#   HTTPS_PORT       published https port        (default 443)
#   APP_HOSTNAME     dashboard hostname          (default runway.localhost)
#   DEPLOY_DOMAIN    wildcard deploy domain      (default deploy.localhost)
#
# From a git checkout, ./install.sh installs in place (no download).

set -euo pipefail

REPO="https://github.com/Dvorinka/runway"
REF="${RUNWAY_VERSION:-${RUNWAY_REF:-main}}"
DIR="${RUNWAY_DIR:-./runway}"

say() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "required tool not found: $1"; }

need curl
need openssl
need docker
docker compose version >/dev/null 2>&1 || die "docker compose plugin not found"

# In-place install: already inside a checkout.
if [ -f Cargo.toml ] && [ -f compose/production.yml ]; then
  DIR="."
else
  if [ ! -f "$DIR/compose/production.yml" ]; then
    say "Downloading runway@$REF"
    mkdir -p "$DIR"
    need tar
    tmp="$(mktemp)"
    curl -fsSL "$REPO/archive/$REF.tar.gz" -o "$tmp"
    tar -xzf "$tmp" --strip-components=1 -C "$DIR"
    rm -f "$tmp"
  else
    say "Existing install found at $DIR — reusing sources"
  fi
fi

ENV_FILE="$DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  say "Generating .env"
  cat > "$ENV_FILE" <<EOF
# Generated by install.sh — edit as needed, never commit.
APP_HOSTNAME=${APP_HOSTNAME:-runway.localhost}
DEPLOY_DOMAIN=${DEPLOY_DOMAIN:-deploy.localhost}
SECRET_KEY=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 24)
HTTP_PORT=${HTTP_PORT:-80}
HTTPS_PORT=${HTTPS_PORT:-443}
# TLS termination: "true" when behind a tunnel/reverse proxy, "false" for
# direct-IP + ACME (then set ACME_EMAIL and publish 443).
DISABLE_TLS=${DISABLE_TLS:-true}
ACME_EMAIL=${ACME_EMAIL:-}
# CGNAT path — set both to auto-manage the instance Cloudflare Tunnel.
CF_API_TOKEN=${CF_API_TOKEN:-}
CF_ACCOUNT_ID=${CF_ACCOUNT_ID:-}
# GitHub App / OAuth (optional — enables repo deploys + login).
GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-}
GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-}
GITHUB_APP_ID=${GITHUB_APP_ID:-}
GITHUB_APP_NAME=${GITHUB_APP_NAME:-}
GITHUB_APP_PRIVATE_KEY=${GITHUB_APP_PRIVATE_KEY:-}
GITHUB_APP_WEBHOOK_SECRET=${GITHUB_APP_WEBHOOK_SECRET:-}
EOF
  chmod 600 "$ENV_FILE"
else
  say ".env exists — keeping it"
fi

say "Building and starting the stack"
docker compose --project-directory "$DIR" --env-file "$ENV_FILE" \
  -f "$DIR/compose/production.yml" up -d --build

HOST="$(grep -E '^APP_HOSTNAME=' "$ENV_FILE" | cut -d= -f2-)"
PORT="$(grep -E '^HTTP_PORT=' "$ENV_FILE" | cut -d= -f2-)"

cat <<EOF

Runway is up.

  Dashboard:  http://${HOST}${PORT:+:$PORT}
  Bootstrap:  docker compose --project-directory $DIR -f $DIR/compose/production.yml \\
                exec runway runway bootstrap --email you@example.com
  Logs:       docker compose --project-directory $DIR -f $DIR/compose/production.yml logs -f

Point DNS at this host (or set CF_API_TOKEN + CF_ACCOUNT_ID in .env and
restart) when APP_HOSTNAME/DEPLOY_DOMAIN move off *.localhost.
EOF
